# Generated by Django 5.0.1 on 2024-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jop',
            name='jop_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
