# Generated by Django 5.0.1 on 2024-01-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jop.category'),
            preserve_default=False,
        ),
    ]
