# Generated by Django 5.0.1 on 2024-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0005_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to='jops/'),
            preserve_default=False,
        ),
    ]
